apiVersion: v1
kind: Service
metadata:
  name: kean-demo-app
  labels:
    app: kean-demo-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: kean-demo-app
